
/* Keeping data in separate file in case it is needed for future use and upgrades */

export const flashcards = [
    { question: 'What is the capital of France?', answer: 'Paris' },
    { question: 'What is the capital of Montenegro?', answer: 'Podgorica' },
     { question: 'What is the capital of Austria?', answer: 'Vienna' },
    { question: 'What is the capital of Belarus?', answer: 'Minsk' },
    { question: 'What is the capital of Belgium?', answer: 'Brussels' },
    { question: 'What is the capital of Bosnia and Herzegovina?', answer: 'Sarajevo' },
    { question: 'What is the capital of Bulgaria?', answer: 'Sofia' },
    { question: 'What is the capital of Croatia?', answer: 'Zagreb' },
    { question: 'What is the capital of Cyprus?', answer: 'Nicosia' },
    { question: 'What is the capital of Czech Republic?', answer: 'Prague' },
    { question: 'What is the capital of Denmark?', answer: 'Copenhagen' },
    { question: 'What is the capital of Estonia?', answer: 'Tallinn' },
    { question: 'What is the capital of Finland?', answer: 'Helsinki' },
    { question: 'What is the capital of Germany?', answer: 'Berlin' },
    { question: 'What is the capital of Greece?', answer: 'Athens' },
    { question: 'What is the capital of Hungary?', answer: 'Budapest' },
    { question: 'What is the capital of Iceland?', answer: 'Reykjavik' },
    { question: 'What is the capital of Ireland?', answer: 'Dublin' },
    { question: 'What is the capital of Italy?', answer: 'Rome' },
    { question: 'What is the capital of Latvia?', answer: 'Riga' },
    { question: 'What is the capital of Liechtenstein?', answer: 'Vaduz' },
    { question: 'What is the capital of Lithuania?', answer: 'Vilnius' },
    { question: 'What is the capital of Luxembourg?', answer: 'Luxembourg' },
    { question: 'What is the capital of Malta?', answer: 'Valletta' },
    { question: 'What is the capital of Moldova?', answer: 'Chișinău' },
    { question: 'What is the capital of Monaco?', answer: 'Monaco' },
    { question: 'What is the capital of Netherlands?', answer: 'Amsterdam' },
    { question: 'What is the capital of North Macedonia?', answer: 'Skopje' },
    { question: 'What is the capital of Norway?', answer: 'Oslo' },
    { question: 'What is the capital of Poland?', answer: 'Warsaw' },
    { question: 'What is the capital of Portugal?', answer: 'Lisbon' },
    { question: 'What is the capital of Romania?', answer: 'Bucharest' },
    { question: 'What is the capital of Russia?', answer: 'Moscow' },
    { question: 'What is the capital of San Marino?', answer: 'San Marino' },
    { question: 'What is the capital of Serbia?', answer: 'Belgrade' },
    { question: 'What is the capital of Slovakia?', answer: 'Bratislava' },
    { question: 'What is the capital of Slovenia?', answer: 'Ljubljana' },
    { question: 'What is the capital of Spain?', answer: 'Madrid' },
    { question: 'What is the capital of Sweden?', answer: 'Stockholm' },
    { question: 'What is the capital of Switzerland?', answer: 'Bern' },
    { question: 'What is the capital of Ukraine?', answer: 'Kyiv' },
    { question: 'What is the capital of United Kingdom?', answer: 'London' },
    { question: 'What is the capital of Vatican City?', answer: 'Vatican City' },
];


